
[main]
log_level = "INFO"
secret_key = "cws6g%yq8NqywOQ9h69QfwCeFi2v3C!s4aR!2cy2Ou*4fzp1sbjHgI8EiHIiuQcnGok74HE#vKEFv!noN5G"
data_directory = "data"

[server]
host = "127.0.0.1"
port = 8000

[database]
source = "sqlite3:data/db.sqlite3"
