[toolchain]
channel = "stable"
components = [ "rust-src", "rust-analyzer", "rustc", "llvm-tools", ]
targets = [
    "wasm32-unknown-unknown",
    "wasm32-wasi",
    "x86_64-pc-windows-gnu",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu"
  ]
profile = "default"
